version: '3.8'
services:

  #defines the container that host the mongo-db server, instantiate the container from the docker hub image
  db-mongo: 
    image: mongo:4.2.8
    container_name: db-mongo
    ports:
      - "4000:27017"
    restart: always


  #instantiate a container from the docker hub image to host rabbit-mq server
  rabbitmq: 
    image: rabbitmq:3.12.4-management
    container_name: rabbitmq
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    expose:
      - "5672"
      - "15672"
    restart: always

  
  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes: # Add volumes so that the code and npm cache are shared to container
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
      - ./video-streaming/videos:/usr/src/app/videos:z
    ports:
     - "4001:80"  #The container's port 80 is mapped to port 4001 on the host machine.
    environment:
      - PORT=80 
      - RABBIT=amqp://guest:guest@rabbitmq:5672
      - NODE_ENV=development                           
    depends_on:
      - rabbitmq           
    restart: "no"


  video-history:
    image: video-history
    build:
      context: ./video-history
      dockerfile: Dockerfile-dev  
    container_name: video-history
    volumes:
      - /tmp/video-history/npm-cache:/root/.npm:z
      - ./video-history/src:/usr/src/app/src:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbitmq:5672    
      - DBHOST=mongodb://db-mongo:27017          
      - DBNAME=history
      - NODE_ENV=development
    depends_on:
      - db-mongo
      - rabbitmq
    restart: "no"  


 
