version: '3'
services:

  aws-storage:
    image: aws-storage
    build: 
      context: ./aws-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "4000:80"   #The container's port 80 is mapped to port 4000 on the host machine.

    environment:
      - PORT=80
      - AWS_ACCESS_KEY_ID=""
      - AWS_SECRET_ACCESS_KEY=""
      - AWS_REGION=""
      - S3_BUCKET_NAME=""
      - S3_FILE_NAME=""
    restart: "no"


  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4001:80"  #The container's port 80 is mapped to port 4001 on the host machine.
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"
