version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db
    ports:
     - "4000:27017"   #Maps the MongoDB standard port 27017 to 4000 on our host OS. We can interact with and check the database on our host using port 4000
    restart: always 


  aws-storage:
    image: aws-storage
    build: 
      context: ./aws-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "4001:80"   #The container's port 80 is mapped to port 4000 on the host machine.
    environment:
      - PORT=80                            # for local dev testing use PORT=3000
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION=
      - S3_BUCKET_NAME=
    restart: "no"


  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4002:80"  #The container's port 80 is mapped to port 4002 on the host machine.
    environment:
      - PORT=80                            # for local dev testing use PORT=4002
      - DBHOST=mongodb://db:27017          # Configures the microservice to connect to the database DBHOST=mongodb://localhost:4000
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage   # for local dev testing use VIDEO_STORAGE_HOST=localhost
      - VIDEO_STORAGE_PORT=80              # for local dev testing use VIDEO_STORAGE_PORT=3000
    depends_on:
      - db  
    restart: "no"
