# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  #config.gui = true
  config.vm.box = "net9/ubuntu-24.04-arm64"
  config.vm.box_version = "1.1"

  config.vm.network "forwarded_port", guest: 4000, host: 4000  # MongoDB 
  config.vm.network "forwarded_port", guest: 4001, host: 4001  # Video-Streaming
  config.vm.network "forwarded_port", guest: 4002, host: 4002  # Video-History

  config.vm.network "forwarded_port", guest: 5672, host: 5672       # Rabbitmq
  config.vm.network "forwarded_port", guest: 15672, host: 15672     # Rabbitmq dashboard

  config.vm.synced_folder "/Users/anjandebnath/Documents/NodeProject/my-new-project", "/home/vagrant/node_project"

  config.vm.provision "shell", path: "./scripts/provision-dev-vm.sh"

  
end
