#Script for building a single image.

# Use an official Node.js runtime as a parent image
FROM node:18.17.1

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy the rest of the project files
COPY ./src ./src

# Command to run the app
#CMD ["npm", "start"]
CMD npx wait-port rabbitmq:5672 && \
    npm start