FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

#Enables caching for npm installs, making subsequent npm installs faster
#Does the npm install when the container starts. This means we can
#make use of npm caching so it’s much faster to install at container startup
#than if we installed it during the build process.
CMD npm ci && npm run start:dev