FROM node:18.17.1

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# RUN npm ci --prefer-offline --no-audit --no-fund
# CMD ["npm", "start"]

CMD npm install --prefer-offline && \
    npx wait-port rabbitmq:5672 && \
    npm run start:dev
