#Script for building a single image.

# Use an amd64 Node.js base image
# FROM --platform=linux/amd64 node:14-alpine3.14
FROM node:14-alpine3.14

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install --only=production


# Copy the rest of the project files
COPY . .
COPY videos/ /app/videos/

# Expose the port the app runs on
EXPOSE 3000

# Copy and configure entrypoint
#COPY docker-entrypoint.sh /usr/local/bin/
#RUN chmod +x /usr/local/bin/docker-entrypoint.sh
#RUN sed -i 's/\r$//' /usr/local/bin/docker-entrypoint.sh # Fix line endings

# Define entrypoint
#ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

# Command to run the app
CMD ["npm", "start"]
